### ISSUE TITLE
Add check for WebVR camera prefab in JS

### ISSUE THREAD

**Issue by caseyyee** [caseyyee/unity-webvr-export#84]
Otherwise user is stuck on loading screen.

**Comment by caseyyee** [comment]
https://github.com/caseyyee/unity-webvr-export/issues/62

**Comment by delapuente** [comment]
I would not block on this. It happens the same if not adding any camera to the scene and using the default template. Although with the default template, the loader hides and a black scene is shown.

**Comment by delapuente** [comment]
Well, it seems what happened is that we didn't remove the loader. I've tested with no cameras and with a regular camera only. With no camera, now the template behaves like the default template. This is an edge case since the editor explicitly warns you that there are no cameras on the scene.

If there is only one camera, everything works but the user can not enter VR. We could still alert in case of no WebVR camera detected but I would prefer to add it to the FAQ section. Not using the VR camera since the beginning could be legit under some circumstances.

**Comment by caseyyee** [comment]
Makes sense.  Will close for now.

**Comment by cvan** [comment]
@caseyyee is there a follow-up issue we can file about this (per our discussion on Slack today)?
